version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    image: ticket-booking-api:dev
    container_name: ticket-booking-api
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./ticketbooking:/app/ticketbooking
      - ./tests:/app/tests
      - ./alembic:/app/alembic
  db:
    image: postgres:14
    container_name: ticket-booking-db
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
