"""empty message

Revision ID: d56d24850f38
Revises: 990e5dee20a9
Create Date: 2023-03-16 23:35:02.715386

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d56d24850f38"
down_revision = "990e5dee20a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("address", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "events",
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "events",
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "ends_at")
    op.drop_column("events", "starts_at")
    op.drop_column("events", "address")
    # ### end Alembic commands ###
