"""empty message

Revision ID: 0bf9b5c2da79
Revises: d56d24850f38
Create Date: 2023-03-17 00:03:18.911953

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0bf9b5c2da79"
down_revision = "d56d24850f38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events_type",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "events", sa.Column("event_type_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "events", "events_type", ["event_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_column("events", "event_type_id")
    op.drop_table("events_type")
    # ### end Alembic commands ###
